"" window size
set lines=52
set columns=144

"" mitame
set guifont=SourceCodePro-Regular:h13
"set guifont=SourceCodePro-Light:h13
"set guifont=Menlo:h13
colorscheme Tomorrow-Night-Eighties

"" hide controls
set guioptions-=T
set guioptions-=m
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L
set guioptions-=b

"" window transparency
set transparency=0
nnoremap <expr><F12> &transparency+10 >= 100 ? ":set transparency=0\<CR>" : ":let &transparency=&transparency+10\<CR>"
