# .zshenv

## language
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

## path
typeset -U path
path=(
  $HOME/bin(N-/)
  /usr/local/bin
  /usr/local/sbin
  /usr/bin
  /usr/sbin
  /bin
  /sbin
)

## editor
export EDITOR=vim
export PAGER='lv -Ia -Ou8 -c'

## golang
export GOPATH=$HOME

## git
export GIT_MERGE_AUTOEDIT=no

